dist: trusty
sudo: required
language: python
python:
  - "3.4"
  - "3.6"
# SUMO ppa can not be added with the apt addon because it is not whitelisted
before_install:
  - sudo add-apt-repository ppa:sumo/stable -y
  - sudo apt-get update -q
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  # Clone SUMO to get newer tools than in the repository
  - git clone --depth 1 https://github.com/planetsumo/sumo.git $TRAVIS_BUILD_DIR/sumo
addons:
  apt:
    sources:
    - 'ppa:sumo/stable'
    packages:
    - libgdal1h
    - gdal-bin
    - libgdal-dev
    - libspatialindex-dev
    - libgeos-dev
    - libopenblas-dev
    - liblapack-dev
    - gfortran
    - sumo
cache: pip
branches:
  except:
  - travis
  - dev
script:
  - coverage run --source=. -m unittest discover
after_success:
  - coverage-badge -f -o .travis/coverage.svg
  - .travis/push.sh
