dist: trusty
sudo: required
language: python
python:
  - "3.4"
  - "3.6"
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - git clone git clone --depth 1 https://github.com/planetsumo/sumo.git $TRAVIS_BUILD_DIR
addons:
  apt:
    packages:
    - libgdal1h
    - gdal-bin
    - libgdal-dev
    - libspatialindex-dev
    - libgeos-dev
    - libopenblas-dev
    - liblapack-dev
    - gfortran
    - sumo
    - sumo-tools
cache: pip
branches:
  except:
  - travis
  - dev
script:
  - coverage run --source=. -m unittest discover
after_success:
  - coverage-badge -f -o .travis/coverage.svg
  - .travis/push.sh
