language: python
python:
  - "3.4"
  - "3.6"
install:
  - pip install -r requirements.txt
before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y libfreetype6-dev libxft-dev libgeos-dev libgdal libspatialindex-dev
script:
  - python -m unittest discover
