language: python
python:
  - "3.4"
  - "3.6"
install:
  - pip install -r requirements.txt
addons:
  apt:
    packages:
    - libgdal1h
    - gdal-bin
    - libgdal-dev
    - libspatialindex-dev
    - libgeos-dev
    - libopenblas-dev
    - liblapack-dev
    - gfortran
script:
  - python -m unittest discover
