dist: trusty
sudo: required
language: python
python:
  - "3.4"
  - "3.6"
env:
# Has to be set so that the TLS coordinator script works
  - SUMO_HOME=$TRAVIS_BUILD_DIR/sumo/sumo
# SUMO ppa can not be added with the apt addon because it is not whitelisted
before_install:
  - sudo add-apt-repository ppa:sumo/stable -y
  - sudo add-apt-repository ppa:jonathonf/ffmpeg-3 -y
  - sudo apt-get update -q
  - sudo apt-get install sumo sumo-tools ffmpeg
install:
  - pip install --upgrade pip
  - pip install -r requirements-test.txt
  # Clone SUMO to get newer tools than in the repository
  - git clone --depth 1 https://github.com/planetsumo/sumo.git $TRAVIS_BUILD_DIR/sumo
  - pip install .
addons:
  apt:
    packages:
    - libgdal1h
    - gdal-bin
    - libgdal-dev
    - libspatialindex-dev
    - libgeos-dev
    - libopenblas-dev
    - liblapack-dev
    - gfortran
    - sumo
cache: pip
branches:
  only:
  - master
# Configure a headless display to test plot generation
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # Give xvfb some time to start
  - sleep 3
script:
  - nosetests --with-coverage --cover-html --cover-tests --cover-package=vtovosm --verbose
after_success:
  - coverage-badge -f -o .travis/coverage.svg
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4 ]]; then .travis/push.sh; fi
